"""init

Revision ID: d4780f9e00dd
Revises: 
Create Date: 2024-10-04 19:43:34.230259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4780f9e00dd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip",
        sa.Column("trip_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pickup", sa.String(), nullable=False),
        sa.Column("dropoff", sa.String(), nullable=False),
        sa.Column("start_time", sa.String(), nullable=False),
        sa.Column("end_time", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("trip_id", name=op.f("pk_trip")),
    )
    op.create_index(op.f("ix_trip_trip_id"), "trip", ["trip_id"], unique=False)
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("telegram", sa.String(), nullable=False),
        sa.Column("password_hash", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_index(op.f("ix_user_user_id"), "user", ["user_id"], unique=False)
    op.create_table(
        "trip_user",
        sa.Column(
            "trip_user_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.trip_id"],
            name=op.f("fk_trip_user_trip_id_trip"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("fk_trip_user_user_id_user"),
        ),
        sa.PrimaryKeyConstraint("trip_user_id", name=op.f("pk_trip_user")),
    )
    op.create_index(
        op.f("ix_trip_user_trip_user_id"),
        "trip_user",
        ["trip_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_user_trip_user_id"), table_name="trip_user")
    op.drop_table("trip_user")
    op.drop_index(op.f("ix_user_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_trip_trip_id"), table_name="trip")
    op.drop_table("trip")
    # ### end Alembic commands ###
